### PR TITLE
For #1873, fix a problem with user history.  Closes #2201.

### LINKED ISSUE #2201: Django Admin:  in TolaUser admin page, countries should be in alphabetical order
I'm only filing the ticket to note that I did this and that it can be undone if need be.

### PR DESCRIPTION
**Pull request by sanjuroj**

### CODE REVIEW

File: js/components/changelog.js [hunk 1]
```diff
@@ -72,43 +73,42 @@ const ChangeLogEntryRowBuilder = ({data}) => {
...
     // If they manage to store a log without any diffs at all, send them to the soft landing place.
-    if (data.diff_list.length === 0){
+    if ((Array.isArray(data.diff_list) && data.diff_list.length === 0) || (Object.keys(data.diff_list).length === 0)) {
         allRows.push(nullRow);
         return allRows
     }
 
     if (data.change_type === 'user_programs_updated') {
         // Create multiple row for program/country changes:
-        if (Object.entries(data.diff_list.countries).length > 0) {
```
Comment (axoplasm) [inline js/components/changelog.js]: why did you remove this condition?

Comment (sanjuroj) [reply js/components/changelog.js]: Ah, yeah.  This is going to be an unnecessarily long story.  I refactored this section before this PR and so I’m not sure if I added this in the first place or if it was there from beginning.  I removed it because the diff list can have a countries object or a programs object.  If the check for a countries object fails and there are program assignments that have changed, they won't show up.
